name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Functions dependencies
      run: |
        cd functions
        npm ci
        
    - name: Build Angular app
      run: npm run build
      
    - name: Run tests (if any)
      run: npm run test:ci
      continue-on-error: true
      
    - name: Deploy to Firebase Hosting
      run: |
        npm install -g firebase-tools
        firebase deploy --token "$FIREBASE_TOKEN" --project theluxvending
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}